### ISSUE TITLE
oidc-middleware needs better issuer error

### ISSUE THREAD

**Issue by rdegges** [okta/okta-oidc-js#230]
I'm using the latest stable release of oidc-middleware in a simple Express.js app and it is now throwing errors in the console.

I've verified this by taking the simplest possible express-generator app and adding JUST our oidc-middleware library to it. Here's what I get upon making a request:

```
(node:6614) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/home/rdegges/Dropbox/Code/testing/blog/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:6614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks like one of our dependencies is throwing some issues. This is a dependency of a dependency. I didn't track it down specifically, but it only occurs when our stuff is plugged into an app, so we should try to figure out what's going on here and resolve it. I'd look into it myself, but am incredibly behind =/

**Comment by rdegges** [comment]
False alarm -- this only  happens if I mistype my `issuer` URL and put `{domain}/oauth/default` instead of `{domain}/oauth2/default`. But... I have to say, that's a really odd error message.

We should have some better error handling here, as the message doesn't convey what is wrong and makes it nearly impossible to debug.

**Comment by rdegges** [comment]
Actually, here's some more info. If the `issuer` URL is mistyped at all, you get really odd errors in the web UI when attempting to login as well:

```
Unknown authentication strategy "oidc"
Error: Unknown authentication strategy "oidc"
    at attempt (/home/rdegges/Dropbox/Code/testing/blog/node_modules/passport/lib/middleware/authenticate.js:173:37)
    at authenticate (/home/rdegges/Dropbox/Code/testing/blog/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at /home/rdegges/Dropbox/Code/testing/blog/node_modules/@okta/oidc-middleware/src/connectUtil.js:79:28
    at Layer.handle [as handle_request] (/home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/index.js:317:13)
    at /home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/index.js:335:12)
    at next (/home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/rdegges/Dropbox/Code/testing/blog/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/rdegges/Dropbox/Code/testing/blog/node_modules/express/lib/router/layer.js:95:5)
```

We should probably fix this since it doesn't make sense to devs or users.

**Comment by robertjd** [comment]
Thanks @rdegges , we definitely want to make this better.

**Comment by webdeveloperpr** [comment]
The error occurs whenever a route returns a rejected promise and there is no .catch block. Some people wrap the async routes with something like this. https://github.com/blakeembrey/async-middleware to fix that issue.

```
(node:6614) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/home/rdegges/Dropbox/Code/testing/blog/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:6614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by michael-basweti** [comment]
I keep getting the following error,i dont know what to do anymore

Unknown authentication strategy "oidc"
Error: Unknown authentication strategy "oidc"
    at attempt (C:\projects\cp-readiness\blog\node_modules\passport\lib\middleware\authenticate.js:173:37)
    at authenticate (C:\projects\cp-readiness\blog\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at C:\projects\cp-readiness\blog\node_modules\@okta\oidc-middleware\src\connectUtil.js:79:28
    at Layer.handle [as handle_request] (C:\projects\cp-readiness\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:335:12)
    at next (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\projects\cp-readiness\blog\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\projects\cp-readiness\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:335:12)
    at next (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (C:\projects\cp-readiness\blog\node_modules\passport\lib\middleware\authenticate.js:325:9)
    at SessionStrategy.authenticate (C:\projects\cp-readiness\blog\node_modules\passport\lib\strategies\session.js:71:10)
    at attempt (C:\projects\cp-readiness\blog\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (C:\projects\cp-readiness\blog\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Layer.handle [as handle_request] (C:\projects\cp-readiness\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:317:13)
    at C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\projects\cp-readiness\blog\node_modules\express\lib\router\index.js:335:12)

**Comment by tusharbudhe0302** [comment]
I think it's design for authorization code flow not for implicit flow.

It's should n't be a bug. Why you don't close this issue. As developer we need do session magnet on server.

This integration depends on sessions to store user information. Ensure the express-session middleware is added before you add ExpressOIDC. By default, the session middleware uses a MemoryStore, which is not designed for production use. Use another session store for production.

https://github.com/expressjs/session#compatible-session-stores

You can close this issue.

**Comment by jmelberg-okta** [comment]
We've introduced a number of [configuration checks](https://github.com/okta/okta-oidc-js/pull/286) in the newest version of `okta/oidc-middleware@1.0.0`. This _should_ help reduce the errors thrown from the downstream dependency.

If issues persist, please provide us with reproduction steps and reopen the issue.

Thanks!
