### ISSUE TITLE
SSR with Okta React

### ISSUE THREAD

**Issue by StefanoSega** [okta/okta-oidc-js#524]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Trying to render my App in SSR doesn't work with SecureRoutes.

Let say I've a routes.tsx file that looks like this:
```
import * as React from 'react';
import { Switch, Route, Redirect } from 'react-router';
import { SecureRoute, ImplicitCallback } from '@okta/okta-react';
import loadable from '@loadable/component';
import LoginContainer from './containers/login/loginContainer';

export default <Switch>
  <SecureRoute exact path="/" component={loadable(() => import('./pages/metricsPage'))} />
  <Route path="/implicit/callback" component={ImplicitCallback} />
  <Route path="/login" component={LoginContainer} />
  <Redirect path="*" to="/" />
</Switch>;
```

... I render it in the front-end this way and works perfectly:
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import { Provider } from 'mobx-react';
import { Security } from '@okta/okta-react';
import routes from './routes';
import stores from './stores';
import App from './components/app';
import { OKTA_CONFIG } from './config';

const AppWithRoutes = () => <BrowserRouter>
  <Security
      issuer={OKTA_CONFIG.securityIssuer}
      client_id={OKTA_CONFIG.clientId}
      redirect_uri={`${window.location.origin}/implicit/callback`}
  >
    <App>
      {routes}
    </App>
  </Security>
</BrowserRouter>;
const AppWithStores = (
  <Provider {...stores}>
    <AppWithRoutes />
  </Provider>);

export default AppWithStores;

if (document) {
  const reactRootDom = document.getElementById('react-main-mount');
  ReactDOM.render(AppWithStores, reactRootDom);
}
```

... for the SSR I've a file apart that I bundle separately with webpack and is dedicated to SSR only; it works like a charm if not for the SecureRoutes; the component part that pass through `ReactDOMServer.renderToString` looks like this:
```
<JssProvider registry={sheetsRegistry} generateClassName={generateClassName}>
      <MuiThemeProvider theme={theme} sheetsManager={sheetsManager}>
        <Provider {...stores}>
          <StaticRouter location={req.url} context={reactRouterContext}>
            <App>
              {routes}
            </App>
          </StaticRouter>
        </Provider>
    </MuiThemeProvider>
  </JssProvider>
```

this way I get an error:
```
TypeError: Cannot read property 'login' of undefined
[0]     at SecureRoute.createRenderWrapper (webpack:///./node_modules/@okta/okta-react/dist/SecureRoute.js?:161:32)
[0]     at Object.eval [as children] (webpack:///./node_modules/react-router/esm/react-router.js?:480:176)
[0]     at ReactDOMServerRenderer.render (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3664:55)
[0]     at ReactDOMServerRenderer.read (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3395:29)
[0]     at Object.renderToString (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3954:27)
[0]     at Module.__webpack_exports__.default (webpack:///./react/ssr.tsx?:68:70)
[0]     at app.get (/Users/stefanosaga/Documents/projects/yoda-ui/server/index.js:110:14)
[0]     at Layer.handle [as handle_request] (/Users/stefanosaga/Documents/projects/yoda-ui/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/stefanosaga/Documents/projects/yoda-ui/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/Users/stefanosaga/Documents/projects/yoda-ui/node_modules/express/lib/router/route.js:112:3)
```

if I wrap <App> with the `<Security>` component I've to specify a static `redirect_uri` and anyway I get the error:
```
(node:23850) UnhandledPromiseRejectionWarning: ReferenceError: location is not defined
[0]     at Auth._callee2$ (webpack:///./node_modules/@okta/okta-react/dist/Auth.js?:175:17)
[0]     at tryCatch (webpack:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js?:62:40)
[0]     at Generator.invoke [as _invoke] (webpack:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js?:296:22)
[0]     at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js?:114:21)
[0]     at step (webpack:///./node_modules/babel-runtime/helpers/asyncToGenerator.js?:17:30)
[0]     at eval (webpack:///./node_modules/babel-runtime/helpers/asyncToGenerator.js?:35:14)
[0]     at new Promise (<anonymous>)
[0]     at new F (webpack:///./node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js?:36:28)
[0]     at Auth.eval (webpack:///./node_modules/babel-runtime/helpers/asyncToGenerator.js?:14:12)
[0]     at Auth.isAuthenticated (webpack:///./node_modules/@okta/okta-react/dist/Auth.js?:212:22)
```

... at this point I don't think I can mock the `location` object giving the correct hash.

## Expected behavior

I expected one of these possible solutions:
* a kind of `StaticSecurity` component to be used for SSR; if I'm hitting a SecuredRoute and the user is not authorized it can answer back with error 401
* a way to get to know if the user is authenticated or not, at that point I can probably handle it redirecting to `/login` if the user is not authenticated. 

## Environment

- Package Version: 1.2.0
- Browser: Chrome
- OS: MacOS Sierra
- Node version (`node -v`): 10.13.0
- Other:

**Comment by swiftone** [comment]
@StefanoSega - Thanks for the detailed report.  Unfortunately, our ReactSDK is not currently built for isomorphic behavior ( because of OIDC redirects and token storage, the client-side/server-side behavior is quite different).  

I'll send this request to my team, but I'm not aware of any plans to support server-side rendering in this library.  Have you examined our server-side SDKs?

**Comment by StefanoSega** [comment]
@swiftone Thanks a lot for the quick reply.

I gave it a look as well I tried to use the OIDC Middleware for NodeJS.
The thing is ... can I retrieve the auth tokens that are stored in React FE but in Node BE instead? Is there a way or FE and BE in this case are totally not related one with the other?

I tried to SSR a component that get `context.auth`, but it cannot get it.
Is there no way to directly access the NodeCache storage?

**Comment by swiftone** [comment]
@StefanoSega - Without delving into the "how"s of your setup it's hard to give a specific answer, and for that I'd suggest our forums(https://devforum.okta.com/), but as a quick stab, you could configure your React FE to use a storage method that you can easily read and transmit, such as "cookie" (see https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#security).  Alternatively, you can use the `this.auth` property on a component using `withAuth` as shown here https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#use-the-access-token.

If those don't apply, I'd suggest first checking with the forums where you'll have a larger audience.  This is an area we want to document better, so if you don't find a good answer there (or if you do and want to mention it here for other users/for us to use as doc material) feel free to recomment here.
