### ISSUE TITLE
[okta-react] it breaks Jest tests within create-react-app 

### ISSUE THREAD

**Issue by mateuszroth** [okta/okta-oidc-js#53]
While using this module, Jest tests fail to run. That's probably because of badly transpiled code from the `okta-react` module. When it is locally transpiled by the `create-react-app`, not Babel within `okta-react` module, it works and Jest tests run.

```
 FAIL  src/main/components/Order/OrderItems/OrderItemsBody.component.test.js
  ● Test suite failed to run

    /Users/mateusz/vd/crm-react/node_modules/@okta/okta-react/dist/Auth.js:54
        value: async function handleAuthentication() {
                     ^^^^^^^^
    SyntaxError: Unexpected token function

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/@okta/okta-react/dist/Security.js:31:13)
      at Object.<anonymous> (node_modules/@okta/okta-react/dist/index.js:8:17)
```

**Comment by lboyette-okta** [comment]
This should resolved in the latest release ([@okta/okta-react@0.0.8](https://www.npmjs.com/package/@okta/okta-react))
