### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers

### ISSUE THREAD

**Issue by johnmeister** [okta/okta-oidc-js#651]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ x] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Shows depreciation warning when setting up new ExpressOIDC

## Expected behavior

not using depreciation. 

## Minimal reproduction of the problem with instructions

npm i @okta/oidc-middleware

const oidc = new ExpressOIDC({
    issuer: _OKTA_URL + '/oauth2/default',
    client_id: _OKTA_CLIENT_ID,
    client_secret: _OKTA_CLIENT_SECRET,
    redirect_uri: 'http://localhost:3000/authorization-code/callback',
    appBaseUrl: 'http://localhost:3000',
    scope: 'openid profile'
});
oidc.on('ready', () => {
    console.log(`Started!`);
return;
});

## Extra information about the use case/user story you are trying to implement
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Trace: DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at module.exports (C:\Sites\website.com\node_modules\timed-out\index.js:9:17)
    at EventEmitter.<anonymous> (C:\Sites\website.com\node_modules\openid-client\node_modules\got\index.js:244:5)
    at Object.onceWrapper (events.js:299:26)
    at EventEmitter.emit (events.js:209:13)
    at makeRequest (C:\Sites\website.com\node_modules\cacheable-request\src\index.js:94:9)
    at C:\Sites\website.com\node_modules\cacheable-request\src\index.js:104:14 {
  name: 'DeprecationWarning',
  code: 'DEP0066'
}
    at process.<anonymous> (C:\Sites\website.com\app.js:45:13)
    at process.emit (events.js:214:15)
    at internal/process/warning.js:52:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

## Environment

- Package Version:
"dependencies": {
        "@okta/oidc-middleware": "^3.0.0",
        "express-session": "^1.17.0",...}

- OS: Windows 10 
- Node version (`node -v`):
12.10.0
- Other:

**Comment by swiftone** [comment]
Thanks for the report @johnmeister - while we investigate, can you confirm the following?

- This is currently a warning and not causing you any blockers (we would like to fix before it does!)
- This is appearing on Windows, you aren't reporting it on other platforms

Thanks!

**Comment by gho** [comment]
@swiftone I'm seeing it on macOS as well.
* Node 12.14.1
* @okta/oidc-middleware 3.0.0
* express 4.17.1
* expression-session 1.17.0

**Comment by swiftone** [comment]
Internal ref: OKTA-272700
