### ISSUE TITLE
Getting Unknown authentication strategy "oidc" from time to time

### ISSUE THREAD

**Issue by jamesnogra** [okta/okta-oidc-js#68]
This is the entire error message:

```
Error: Unknown authentication strategy "oidc"
    at attempt (C:\wamp64\www\RVSlinkyLinks\node_modules\passport\lib\middleware\authenticate.js:173:37)
    at authenticate (C:\wamp64\www\RVSlinkyLinks\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at C:\wamp64\www\RVSlinkyLinks\node_modules\@okta\oidc-middleware\src\connectUtil.js:74:28
    at Layer.handle [as handle_request] (C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\index.js:317:13)
    at C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\index.js:335:12)
    at next (C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\wamp64\www\RVSlinkyLinks\node_modules\@okta\oidc-middleware\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\wamp64\www\RVSlinkyLinks\node_modules\express\lib\router\layer.js:95:5)
```

What's weird is that on my work computer (locally), this rarely comes out but still, it pops from time to time. But on my home laptop (still locally), I always get this error. I cannot go to /login page. I have installed Okta using "npm install @okta/oidc-middleware" in both environments. I can also test that this library is working because if I try to change any parameter in the ExpressOIDC constructor, I get an error. Both my work and home laptop are running Windows 10.

**Comment by lboyette-okta** [comment]
The inconsistency sounds like a race condition. Ensure you're waiting for the `ready` event before starting your app:

https://github.com/okta/okta-oidc-js/tree/master/packages/oidc-middleware#usage-example
```
const app = express();
const oidc = new ExpressOIDC({
  issuer: 'https://{yourOktaDomain}.com/oauth2/default',
  client_id: 'XXXXX',
  client_secret: 'XXXXX',
  redirect_uri: 'http://localhost:3000/authorization-code/callback',
  scope: 'openid profile'
});

oidc.on('ready', () => {
  app.listen(3000, () => console.log('app started'));
});
```

**Comment by jamesnogra** [comment]
Thanks for the quick reply. My code goes like this, so where should I put the oidc.on('ready', function() {}); ?

```
app.set('view engine', 'pug');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

//this is for okta
const session = require('express-session');
const { ExpressOIDC } = require('@okta/oidc-middleware');
// session support is required to use ExpressOIDC
app.use(session({
    secret: 'a2AE254b5Ad981C40622D49F9Ac2E4F1565C9x!048F59f27BD9C8$8900D5C0D8',
    resave: true,
    saveUninitialized: false
}));
const oidc = new ExpressOIDC({
    issuer: 'https://dev-346920.oktapreview.com/oauth2/default',
    client_id: '0oaczrjeueiua1WMS0h7',
    client_secret: 'culijUMDlOP3_8r9_m8uS7gjr5oKbJebhKqm-yTQ',
    redirect_uri: 'http://localhost:3000/authorization-code/callback',
    scope: 'openid profile'
});

// ExpressOIDC will attach handlers for the /login and /authorization-code/callback routes
app.use(oidc.router);
app.get('/logout', function(req, res, next) {
    req.logout();
    return res.redirect('/slinky-links/links/all');
});
app.use('/', index);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```

**Comment by lboyette-okta** [comment]
Somewhere in your application, you'll call `app.listen`. You'll need to restructure your app to have access to the `oidc` object, so you can call `oidc.on('ready', () => {})`

Also, you may want to reset your session secret and client_secret if this will be production code (they were emailed to anyone listening to changes on this repo)

**Comment by jamesnogra** [comment]
Thank you for your help.

**Comment by hampsterx** [comment]
This should be noted in the official documentation!

**Comment by austinksmith** [comment]
App.listen is called from within the npm express lib package, is there an updated suggestion on how to change this? I do not want to have to modify the express server npm package and then be stuck unable to update in the future. 

I am running into this issue even on the provided example implementation package, https://developer.okta.com/blog/2018/08/17/build-and-understand-user-authentication-in-node

Directly cloned the repo, ran npm install, added my okta credentials and still ran into this problem. I think the documentation and provided examples are really out of date.

**Comment by abhineet11** [comment]
is this issue still open. Getting Error: Unknown authentication strategy "oidc"
