### ISSUE TITLE
AssertionError: id_token issued in the future in Live Server

### ISSUE THREAD

**Issue by jamesnogra** [okta/okta-oidc-js#69]
Full error details:

AssertionError: id_token issued in the future
    at Client.validateIdToken (/var/www/html/rvseo-data/node_modules/openid-client/lib/client.js:469:7)
    at grant.then.then.tokenset (/var/www/html/rvseo-data/node_modules/openid-client/lib/client.js:333:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)

This is the error I always get on my test server whenever I finish logging in. This error appears in the /authorization-code/callback. I don't get this error message locally and I'm afraid that when going production, this error appears all the time.

**Comment by lboyette-okta** [comment]
Timing issues like this are usually caused by clock drift; you're not guaranteed the time on your computer/server is the same as Okta's servers.

We should add some wiggle room (5 min is the default on Windows) and make this configurable.

**Comment by silkimen** [comment]
+1
