### ISSUE TITLE
ExpressOIDC Configuration : Request timed out

### ISSUE THREAD

**Issue by shirishp** [okta/okta-oidc-js#82]
I am seeing following error from time to time. It works sometimes and app starts, but most of the times I see this error within 2-3 seconds of starting the app.

Is there a way to increase the timeout?

```
Unable to configure ExpressOIDC { RequestError: Request timed out
    at timeoutFn (.../node_modules/got/index.js:285:53)
    at asPromise (.../node_modules/got/index.js:355:18)
    at got (.../node_modules/got/index.js:578:10)
    at Function.got.(anonymous function) [as get] (.../node_modules/got/index.js:596:31)
    at Object.get (.../node_modules/openid-client/lib/http.js:15:14)
    at Function.discover (.../node_modules/openid-client/lib/issuer.js:192:28)
    at Object.oidcUtil.createClient.context [as createClient] (.../node_modules/@okta/oidc-middleware/src/oidcUtil.js:30:17)
    at new ExpressOIDC (.../node_modules/@okta/oidc-middleware/src/ExpressOIDC.js:109:14)
    at Object.<anonymous> (.../src/app.js:20:14)
    at Module._compile (module.js:660:30)
    at loader (.../node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: '<DOMAIN>.oktapreview.com',
  hostname: '<DOMAIN>.oktapreview.com',
  method: 'GET',
  path: '/oauth2/default/.well-known/openid-configuration',
  protocol: 'https:',
  url: 'https://<DOMAIN>.oktapreview.com/oauth2/default/.well-known/openid-configuration' }
```

Following is the code of my app

```javascript
import express from 'express';
import session from 'express-session';
import {ExpressOIDC} from '@okta/oidc-middleware';
import {APP_SECRET, PORT} from './config/appConfig';

const app = express();

app.use(session({
  secret: APP_SECRET,
  resave: true,
  saveUninitialized: false,
}));

const oidc = new ExpressOIDC({
  issuer: 'https://<DOMAIN>.oktapreview.com/oauth2/default',
  client_id: '<CLIENT_ID>',
  client_secret: '<CLIENT_SECRET>',
  redirect_uri: 'http://localhost:3000/authorization-code/callback',
  scope: 'openid profile',
});
app.use(oidc.router);

app.get('/', (req, res) => {
  if (req.userinfo) {
    console.log(req.userinfo);
    res.send(`Hello ${req.userinfo.name}! <a href="logout">Logout</a>`);
  } else {
    res.send('Please <a href="/login">login</a>');
  }
});

app.get('/protected', oidc.ensureAuthenticated(), (req, res) => {
  res.send('Top Secret');
});

app.get('/logout', (req, res) => {
  req.logout();
  res.redirect('/');
});

oidc.on('ready', () => {
  app.listen(PORT, () => console.log('App Started'));
});

oidc.on('error', (err) => {
  console.log('Unable to configure ExpressOIDC', err);
});

```

**Comment by robertjd** [comment]
Hi @shirishp 

It looks like the underlying `openid-client` allows you to configure it's HTTP mechanism, can you try adding this to your code before you require our module:

```
const openIdClient = require('openid-client');

// ten seconds as milliseconds, configure as needed:

openIdClient.Issuer.defaultHttpOptions.timeout = 10000; 
```

This seems to change the needed setting.  I tested locally by setting it to 1 and I get the timeout error immediately.

Pulled from these docs:

https://www.npmjs.com/package/openid-client#changing-http-request-defaults

**Comment by jamesnogra** [comment]
Here's my full code for app.js

```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var http = require('http');

var index = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

//this is for okta
const session = require('express-session');
const { ExpressOIDC } = require('@okta/oidc-middleware');
// session support is required to use ExpressOIDC
app.use(session({
    secret: 'XXXXXXXXX',
    resave: true,
    saveUninitialized: false
}));
const oidc = new ExpressOIDC({
    issuer: 'https://dev-xxxxx.oktapreview.com/oauth2/default',
    client_id: 'xxxxxx',
    client_secret: 'xxxxxxxxxx',
    redirect_uri: 'http://localhost:3000/authorization-code/callback',
    scope: 'openid profile'
});

// ExpressOIDC will attach handlers for the /login and /authorization-code/callback routes
app.use(oidc.router);
app.get('/logout', function(req, res, next) {
    req.logout();
    return res.redirect('/slinky-links/links/all');
});
app.use('/', index);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

**const openIdClient = require('openid-client');
openIdClient.Issuer.defaultHttpOptions.timeout = 10000;** 

oidc.on('ready', () => {
//oidc.on('error', err => {
  app.listen(3000, () => console.log('App Started!'));
});

module.exports = app;
```

**Comment by shirishp** [comment]
Thanks @robertjd. I will try this.
IMHO okta-oidc should expose a configuration option for that.

**Comment by Shogan** [comment]
Also running into this exact same error, but only when running in a docker container in AWS Fargate... Running the same container locally or outside of a container under node on my workstation and it works just fine.

**Comment by robertjd** [comment]
Thanks all, the new 0.1.0 version of this library has set the default timeout to 10 seconds and made it easier to configure.

**Comment by shirishp** [comment]
Thanks @robertjd

**Comment by AliHaghani** [comment]
@robertjd Are there any updated docs on configuring the HTTP mechanism (i.e. proxies) for the newest version of ExpressOIDC?

`custom.setHttpOptionsDefaults` as outlined [here](https://github.com/panva/node-openid-client/blob/master/docs/README.md#customizing) seems to have no effect on the requests going out.
