### ISSUE TITLE
JWT verifier 

### ISSUE THREAD

**Issue by hannyM** [okta/okta-oidc-js#824]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by hannyM** [comment]
I using @okta/jwt-verifier, at my local all seems working as expected but on linux machine, shared error is showed 
Pointing below snippet of the lib.js 
const {
  assertIssuer,
  assertClientId
} = require('@okta/configuration-validation');


SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/opt/cqt/server/node-v4.4.0-linux-x64/lib/node_modules/pm2/node_modules/                                                              pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)


Could anyone please help me out. to get my issue resolved

**Comment by shuowu** [comment]
@hannyM I suspect it's because you don't have the up to date node version on the Linux machine to support the ES6 syntax. Upgrade the node version may solve this issue.

**Comment by vejandla** [comment]
@hannyM Are you stripping of "Bearer " from the header? I've seen this error when I did not strip that string. 🤷‍♂️

**Comment by swiftone** [comment]
Closing as apparently resolved with an ES6 compatible version of node (or babel transpilation).  If problems persist feel free to reopen with additional details.
